import { GameData } from "@/context/interface";

const ROOT_PATH = "/images/games/";

export const DUMMY_GAME_LIST: GameData = {
  "1": {
    id: "1",
    name: "Anaconda Wild 2",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}anaconda-wild-2.png`,
  },
  "2": {
    id: "2",
    name: "Aztec Bonus Lines",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}aztec-bonus-lines.png`,
  },
  "3": {
    id: "3",
    name: "Beach Life",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}beach-life.png`,
  },
  "4": {
    id: "4",
    name: "Big Bad Wolf",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}big-bad-wolf.png`,
  },
  "5": {
    id: "5",
    name: "Book of Egypt",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}book-of-egypt.png`,
  },
  "6": {
    id: "6",
    name: "Crocodile Blitz Xtreme FB",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}crocodile-blitz-xtreme-fb.png`,
  },
  "7": {
    id: "7",
    name: "Inca Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}inca-jackpot.png`,
  },
  "8": {
    id: "8",
    name: "Maya Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}maya-jackpot.png`,
  },
  "9": {
    id: "9",
    name: "Pirates Power",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}pirates-power.png`,
  },
  "10": {
    id: "10",
    name: "Shaolin Crew",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}shaolin-crew.png`,
  },
  "11": {
    id: "11",
    name: "Sugar Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}sugar-rush.png`,
  },
  "12": {
    id: "12",
    name: "Pride Of Persia",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}pride-of-persia.png`,
  },
  // Repeated entries with updated IDs
  "13": {
    id: "13",
    name: "Anaconda Wild 2",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}anaconda-wild-2.png`,
  },
  "14": {
    id: "14",
    name: "Aztec Bonus Lines",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}aztec-bonus-lines.png`,
  },
  "15": {
    id: "15",
    name: "Beach Life",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}beach-life.png`,
  },
  "16": {
    id: "16",
    name: "Big Bad Wolf",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}big-bad-wolf.png`,
  },
  "17": {
    id: "17",
    name: "Book of Egypt",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}book-of-egypt.png`,
  },
  "18": {
    id: "18",
    name: "Crocodile Blitz Xtreme FB",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}crocodile-blitz-xtreme-fb.png`,
  },
  "19": {
    id: "19",
    name: "Inca Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}inca-jackpot.png`,
  },
  "20": {
    id: "20",
    name: "Maya Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}maya-jackpot.png`,
  },
  "21": {
    id: "21",
    name: "Pirates Power",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}pirates-power.png`,
  },
  "22": {
    id: "22",
    name: "Shaolin Crew",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}shaolin-crew.png`,
  },
  "23": {
    id: "23",
    name: "Sugar Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}sugar-rush.png`,
  },
  "24": {
    id: "24",
    name: "Pride Of Persia",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}pride-of-persia.png`,
  },
  "25": {
    id: "25",
    name: "Anaconda Wild 2",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}anaconda-wild-2.png`,
  },
  "26": {
    id: "26",
    name: "Aztec Bonus Lines",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}aztec-bonus-lines.png`,
  },
  "27": {
    id: "27",
    name: "Beach Life",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}beach-life.png`,
  },
  "28": {
    id: "28",
    name: "Big Bad Wolf",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}big-bad-wolf.png`,
  },
  "29": {
    id: "29",
    name: "Book of Egypt",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}book-of-egypt.png`,
  },
  "30": {
    id: "30",
    name: "Crocodile Blitz Xtreme FB",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}crocodile-blitz-xtreme-fb.png`,
  },
  "31": {
    id: "31",
    name: "Inca Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}inca-jackpot.png`,
  },
  "32": {
    id: "32",
    name: "Maya Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}maya-jackpot.png`,
  },
  "33": {
    id: "33",
    name: "Pirates Power",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}pirates-power.png`,
  },
  "34": {
    id: "34",
    name: "Shaolin Crew",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}shaolin-crew.png`,
  },
  "35": {
    id: "35",
    name: "Sugar Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}sugar-rush.png`,
  },
  "36": {
    id: "36",
    name: "Pride Of Persia",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}pride-of-persia.png`,
  },
  "37": {
    id: "37",
    name: "Anaconda Wild 2",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}anaconda-wild-2.png`,
  },
  "38": {
    id: "38",
    name: "Aztec Bonus Lines",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}aztec-bonus-lines.png`,
  },
  "39": {
    id: "39",
    name: "Beach Life",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}beach-life.png`,
  },
  "40": {
    id: "40",
    name: "Big Bad Wolf",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}big-bad-wolf.png`,
  },
  "41": {
    id: "41",
    name: "Book of Egypt",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}book-of-egypt.png`,
  },
  "42": {
    id: "42",
    name: "Crocodile Blitz Xtreme FB",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}crocodile-blitz-xtreme-fb.png`,
  },
  "43": {
    id: "43",
    name: "Inca Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}inca-jackpot.png`,
  },
  "44": {
    id: "44",
    name: "Maya Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}maya-jackpot.png`,
  },
  "45": {
    id: "45",
    name: "Pirates Power",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}pirates-power.png`,
  },
  "46": {
    id: "46",
    name: "Shaolin Crew",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}shaolin-crew.png`,
  },
  "47": {
    id: "47",
    name: "Sugar Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}sugar-rush.png`,
  },
  "48": {
    id: "48",
    name: "Pride Of Persia",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}pride-of-persia.png`,
  },
  "49": {
    id: "49",
    name: "Anaconda Wild 2",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}anaconda-wild-2.png`,
  },
  "50": {
    id: "50",
    name: "Aztec Bonus Lines",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}aztec-bonus-lines.png`,
  },
  "51": {
    id: "51",
    name: "Beach Life",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}beach-life.png`,
  },
  "52": {
    id: "52",
    name: "Big Bad Wolf",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}big-bad-wolf.png`,
  },
  "53": {
    id: "53",
    name: "Book of Egypt",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}book-of-egypt.png`,
  },
  "54": {
    id: "54",
    name: "Crocodile Blitz Xtreme FB",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}crocodile-blitz-xtreme-fb.png`,
  },
  "55": {
    id: "55",
    name: "Inca Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}inca-jackpot.png`,
  },
  "56": {
    id: "56",
    name: "Maya Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}maya-jackpot.png`,
  },
  "57": {
    id: "57",
    name: "Pirates Power",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}pirates-power.png`,
  },
  "58": {
    id: "58",
    name: "Shaolin Crew",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}shaolin-crew.png`,
  },
  "59": {
    id: "59",
    name: "Sugar Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}sugar-rush.png`,
  },
  "60": {
    id: "60",
    name: "Pride Of Persia",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}pride-of-persia.png`,
  },
};
